# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_key', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('handlers', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('mis_type', models.CharField(max_length=30)),
                ('mis_data', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=30)),
                ('interface_type', models.CharField(max_length=30)),
                ('mac', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
                ('subnet_mask', models.CharField(max_length=30)),
                ('gateway', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Storage_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_space', models.CharField(max_length=30)),
                ('total_space', models.CharField(max_length=30)),
                ('eq_status', models.CharField(max_length=30)),
                ('disk_status', models.CharField(max_length=30)),
                ('disk_type', models.CharField(max_length=30)),
            ],
        ),
    ]
