# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdm_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='pwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='userid',
            new_name='username',
        ),
    ]
