# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdm_data', '0003_auto_20180321_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
