# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdm_data', '0004_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('bucket', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('targer_bucket', models.CharField(max_length=300)),
                ('target_region', models.CharField(max_length=300)),
                ('target_path', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='Storage_data',
            new_name='Storagedata',
        ),
        migrations.RemoveField(
            model_name='active',
            name='id',
        ),
        migrations.RemoveField(
            model_name='network',
            name='id',
        ),
        migrations.AlterField(
            model_name='active',
            name='act_key',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='log',
            name='mis_data',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='network',
            name='interface',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
