# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdm_data', '0005_auto_20180328_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_use', models.CharField(max_length=30)),
                ('cpu_use', models.CharField(max_length=30)),
                ('mem_use', models.CharField(max_length=30)),
            ],
        ),
    ]
