# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdm_data', '0006_graphdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
