# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdm_data', '0008_auto_20180402_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphdata',
            old_name='net_use',
            new_name='cpu_use',
        ),
    ]
